# Generated by Django 4.2.2 on 2023-07-08 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedido_productos_productocomprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, 1)),
            preserve_default=False,
        ),
    ]
