# Generated by Django 4.2.2 on 2023-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedido_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
