# Generated by Django 4.2.2 on 2023-07-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Preparando', 'Preparando'), ('Enviado', 'Enviado'), ('Recibido', 'Recibido')], default='Ingresado'),
        ),
    ]
