# Generated by Django 4.2.2 on 2023-06-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_alter_appuser_ciudad_alter_appuser_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('telefono', models.IntegerField(null=True)),
            ],
        ),
    ]
