# Generated by Django 4.2.2 on 2023-07-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.CharField(max_length=400, verbose_name='Productos'),
        ),
    ]
